#!/bin/bash
# Helper-script to update the pioasm-generated files in pico-examples repo
PIOASM_COMMENT_STRING="This file is autogenerated by pioasm"
if [ -z $PICO_SDK_PATH ]; then
  echo "PICO_SDK_PATH envvar not set"
  exit 1
fi
if [ ! -d $PICO_SDK_PATH ]; then
  echo "PICO_SDK_PATH envvar ($PICO_SDK_PATH) is invalid"
  exit 1
fi
# convert to absolute path
PICO_SDK_PATH=$(realpath $PICO_SDK_PATH)
BUILD_DIR=$(mktemp -d -p .)
cleanup() {
  if [[ -d "$BUILD_DIR" ]]; then
    rm -rf "$BUILD_DIR"
  fi
}
trap cleanup EXIT
SCRIPTNAME=$(basename "$0")
PIOASM_OUTPUT_DIRS=()
while read -r DIRNAME; do
  if [ "$DIRNAME" != "$SCRIPTNAME" ]; then
    PIOASM_OUTPUT_DIRS+=("$DIRNAME")
  fi
done <<< "$(git grep -l "$PIOASM_COMMENT_STRING" | cut -d/ -f1-2 | sort | uniq)"
while read -r FILENAME; do
  if [ "$FILENAME" != "$SCRIPTNAME" ]; then
    rm "$FILENAME"
  fi
done <<< "$(git grep -l "$PIOASM_COMMENT_STRING")"
cmake -S . -B "$BUILD_DIR" -DPICO_SDK_PATH=$PICO_SDK_PATH -DPICO_NO_PICOTOOL=1
for DIRNAME in "${PIOASM_OUTPUT_DIRS[@]}"; do
  make -j4 -C "$BUILD_DIR/$DIRNAME"
done
cleanup
